spring.application.name=pharma web services

# H2 Database
spring.datasource.url=jdbc:h2:mem:pharma_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Load data.sql after Hibernate creates tables
spring.jpa.defer-datasource-initialization=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Server
server.port=8080

server.forward-headers-strategy=framework

app.openapi.title=NextGen Ecommerce Service API
app.openapi.description=REST API for managing NextGen ecommerce products
app.openapi.version=1.0.0